import { MentionTypes, MediaTypes } from "@/enums/templates/mentions";

export const allCityMentions: Array<cityMention> = [
  // {
  //   title: "Parmenter offers a fine farewell",
  //   author: "Brenda Harwood",
  //   company: "Otago Daily Times",
  //   date: "Sep 22",
  //   link: "https://www.odt.co.nz/the-star/parmenter-offers-fine-farewell",
  //   shortDescription: "Short Description 1",
  //   thumbnailPath: "images/common/placeholder.svg",
  //   readingtimeMins: 6,
  //   mentionTypes: [MentionTypes.News, MentionTypes.Blog],
  //   mediaTypes: [MediaTypes.Text, MediaTypes.Video],
  // },
  // {
  //   title: "Having a ball to celebrate residency end",
  //   author: "John Lewis",
  //   company: "Otago Daily Times",
  //   date: "Sep 22",
  //   link: "https://www.odt.co.nz/news/dunedin/campus/having-ball-celebrate-residency-end",
  //   shortDescription: "Short Description 1",
  //   thumbnailPath: "images/common/placeholder.svg",
  //   readingtimeMins: 6,
  //   mentionTypes: [MentionTypes.News, MentionTypes.Blog],
  //   mediaTypes: [MediaTypes.Text, MediaTypes.Video],
  // },
  // {
  //   title: "Back home, time to dance",
  //   author: "John Lewis",
  //   company: "Otago Daily Times",
  //   date: "Sep 22",
  //   link: "https://www.odt.co.nz/entertainment/dance/back-home-time-dance",
  //   shortDescription: "Short Description 1",
  //   thumbnailPath: "images/common/placeholder.svg",
  //   readingtimeMins: 6,
  //   mentionTypes: [MentionTypes.News, MentionTypes.Blog],
  //   mediaTypes: [MediaTypes.Text, MediaTypes.Video],
  // },
  // {
  //   title: "Back home, time to dance",
  //   author: "John Lewis",
  //   company: "Otago Daily Times",
  //   date: "Sep 22",
  //   link: "https://www.odt.co.nz/entertainment/dance/back-home-time-dance",
  //   shortDescription: "Short Description 1",
  //   thumbnailPath: "images/common/placeholder.svg",
  //   readingtimeMins: 6,
  //   mentionTypes: [MentionTypes.News, MentionTypes.Blog],
  //   mediaTypes: [MediaTypes.Text, MediaTypes.Video],
  // },
  // {
  //   title: "Back home, time to dance",
  //   author: "John Lewis",
  //   company: "Otago Daily Times",
  //   date: "Sep 22",
  //   link: "https://www.odt.co.nz/entertainment/dance/back-home-time-dance",
  //   shortDescription: "Short Description 1",
  //   thumbnailPath: "images/common/placeholder.svg",
  //   readingtimeMins: 6,
  //   mentionTypes: [MentionTypes.News, MentionTypes.Blog],
  //   mediaTypes: [MediaTypes.Text, MediaTypes.Video],
  // },
  // {
  //   title: "Back home, time to dance",
  //   author: "John Lewis",
  //   company: "Otago Daily Times",
  //   date: "Sep 22",
  //   link: "https://www.odt.co.nz/entertainment/dance/back-home-time-dance",
  //   shortDescription: "Short Description 1",
  //   thumbnailPath: "images/common/placeholder.svg",
  //   readingtimeMins: 6,
  //   mentionTypes: [MentionTypes.News, MentionTypes.Blog],
  //   mediaTypes: [MediaTypes.Text, MediaTypes.Video],
  // },
];
